### ISSUE TITLE
Creating conda environment from environment.yml fails to install ipykernel 6.18.0

### ISSUE THREAD

**Issue by cstephen** [ua-snap/snap-geo#4]
When attempting to create the `snap-geo` conda environment from the `environment.yml` file from the `add_conda_env` branch, on an Atlas compute node (atlas15 in this case), it failed to install the `ipykernel` package:

```
$ conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - ipykernel=6.18.0
```

I'm not sure why it fails, but I got around this by changing `environment.yml` to install ipykernel 6.15.2 instead.

**Comment by kyleredilla** [comment]
huh, weird, failed for me as well and must no longer be available in either conda-forge or default channels I guess. I've updated the env spec to use 6.15.2, which worked for me as well.
